config/routes.rb
Wiim::Application.routes.draw do
  root :to                     => 'home#index'
  get 'brands.json'            => 'brands#index'
  get 'brands/new'             => 'brands#new',        as: 'new_brand'
  post 'brands'                => 'brands#create'
  get 'brands/:id'             => 'brands#show'

  get 'admin'                 => 'admin#index',      as: 'admin_index'
  get 'admin/submissions/:id' => 'admin#submission', as: 'brand_submission'
  get 'admin/submissions'     => 'admin#submissions', as: 'brands_submissions'
  put 'admin/submissions/approve/:id' => 'admin#approve',    as: 'brand_approval'
  put 'admin/submissions/reject/:id' => 'admin#reject',    as: 'brand_rejection'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates_associated :countries
  validates_associated :categories
  validates_presence_of :countries
  validates_presence_of :categories
  validates_presence_of :name
  validates_uniqueness_of :name
  validates :status, inclusion: { in: %w(approved pending rejected) }
  validates :url, format: { with: /\Ahttp(s?):\/\/|\A\z/ }

  attr_accessible :name, :url, :description, :countries, :categories

  has_and_belongs_to_many :countries
  has_and_belongs_to_many :categories

  include Tire::Model::Search

  index_name "wiim-#{Rails.env}"

  def to_indexed_json
    BrandsSerializer.serialize(self).to_json
  end

  after_save do
    if status == 'approved'
      update_index 
    else
      Brand.index.remove self
    end
  end

  def approve
    self.status = 'approved'
    save!
  end

  def reject
    self.status = 'rejected'
    save!
  end

  def self.approved
    where(status: 'approved')
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  validates :name, inclusion: {in: Wiim::Application.config.categories}

  attr_accessible :name

  has_and_belongs_to_many :brands
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  validates :name, inclusion: {in: Wiim::Application.config.countries}

  attr_accessible :name

  has_and_belongs_to_many :brands
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :authenticate

  def index
  end

  def submissions
    @brands = Brand.order(:name)
  end

  def submission
    brand_record = Brand.find(params[:id])
    @brand = BrandsSerializer.make_struct(brand_record)
    @status = Brand.find(params[:id]).status
  end

  def approve
    brand = Brand.find(params[:id])
    brand.approve
    redirect_to brands_submissions_path
  end

  def reject
    brand = Brand.find(params[:id])
    brand.reject
    redirect_to brands_submissions_path
  end

  protected

  def authenticate
    authenticate_or_request_with_http_digest do |username|
      ENV['WIIM_PASS'] if username == ENV['WIIM_USERNAME']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    brands = Brand.approved.includes(:categories, :countries)
    render json: BrandsSerializer.serialize(brands).to_json
  end

  def show
    @brand = Brand.search("id: #{params[:id]}").first
  end

  def new
    @brand = Brand.new
    @countries = Country.all
    @categories = Category.all
  end

  def create
    @brand = BrandBuilder.build params

    if @brand.save
      flash[:notice] = "Thank you for creating a new brand! We will be reviewing it shortly..."
      redirect_to '/'
    else
      flash[:error] = @brand.errors
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    query = params['query'] || '?'
    @approved_brands = Brand.search query
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def display_status(status)
    case status
    when 'approved'; 'success'
    when 'pending'; 'info'
    when 'rejected'; 'error'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/submission.html.erb
<div class="container admin">
  <%= render 'shared/brand', brand: @brand, full_description: false %>
  <hr/>
  <p><strong><%= @status.capitalize %></strong></p>
  <%= render 'shared/approval_btn', brand: @brand %>
</div>

app/views/admin/submissions.html.erb
<div class="container">
  <p>Welcome to the admin dashboard. Please review the submitted brands:</p>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @brands.each do |brand| %>
        <tr>
          <td><%= link_to brand.name, brand_submission_path(brand.id) %></td>
          <td class="text-<%= display_status(brand.status) %>"><%= brand.status %></td>
          <td><%= render 'shared/approval_btn', brand: brand %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/brands/_multiple_options_select.html.erb
<div id="<%= attribute %>-chooser" class="multiple-choice-container">
  <select class="chzn-select" data-placeholder="Choose one or more <%= attribute.pluralize %>" style="dislay:none" multiple="" name="<%= attribute.pluralize %>[]">
    <% attribute.capitalize.constantize.all.map(&:name).each do |value| %>
      <option value="<%= value %>"><%= value %></option>
    <% end %>
  </select>
</div>
<div class="clearfix"></div>

app/views/brands/new.html.erb
<div class="container" id="brand-submission-container">
  <% if flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      Sorry, we could not create a new brand because :
      <ul>
        <% flash[:error].full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
      Please correct these fields and submit again!
    </div>
  <% end %>
  <%= form_for @brand, html: { class: 'form-horizontal' } do |f| %>
    <fieldset>
      <legend>1. Which brand are you submitting?</legend>
      <div class="control-group">
        <%= f.label :name, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :url, 'Website', class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :url %>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>2. Tell us a bit more about what it is and what it makes</legend>
      <%= f.text_area :description, placeholder: 'Enter a description ...', id: 'description-field', rows: 5 %>
      <div class="form-spacer"></div>
      <%= render 'multiple_options_select', attribute: 'category' %>
    </fieldset>

    <fieldset>
      <legend>3. Tell us where it is made!</legend>
      <%= render 'multiple_options_select', attribute: 'country' %>
    </fieldset>
    <div class="form-spacer"></div>


    <%= f.submit 'Submit!', class: 'btn' %>
  <% end %>
</div>

app/views/brands/show.html.erb
<div class='container'>
  <%= render 'shared/brand', brand: @brand, full_description: false %>
</div>

app/views/home/index.html.erb
<header id="overview">
  <div class="container">
    <h1>Where Is It Made ?</h1>
    <p class="lead">Find out where your favourite products are made</p>
    <%= form_tag :root, method: :get, class: 'form-search' do %>
      <%= text_field_tag 'query', params['query'], id: 'search-form', class: 'search-query' %>
      <button type="submit" class="btn btn-primary">Search</button>
    <% end %>
  </div>
</header>
<div class="home-separator"></div>
<div class="container" id="brands">
  <% @approved_brands.each do |brand| %>
    <%= render 'shared/brand', brand: brand, full_description: true %>
    <% unless brand == @approved_brands.to_a.last %>
      <hr/>
    <% end %>
  <% end %>
</div>
<div class="clearfix"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiim</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= render 'shared/ga' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <a href="/" class="brand">Where is it made ?</a>
          <ul class="nav">
            <li><a href="<%= new_brand_path %>">Submit a new brand </a></li>
          </ul>
        </div>
      </div>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <div class="container"><%= flash[:notice] %></div>
      </div>
    <% end %>

    <%= yield %>
      
    <hr/>
    <footer>
      <div class="container">
        <ul class="footer-links pull-left">
          <li><a href='<%= brands_submissions_path %>'>Admin</a></li>
        </ul>
        <ul class="footer-links pull-right">
          <li><a href="#">How it works</a></li>
          <li class="muted">·</li>
          <li><a href="#">About</a></li>
        </ul>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_approval_btn.html.erb
<% unless brand.status == 'approved' %>
  <%= form_tag brand_approval_path(brand.id), method: :put, class: 'pull-left approve-btn'  do %>
    <%= button_tag "Approve", class: 'btn' %>
  <% end %>
<% end %>
<% unless brand.status == 'rejected' %>
  <%= form_tag brand_rejection_path(brand.id), method: :put, class: 'pull-left'  do %>
    <%= button_tag "Reject", class: 'btn' %>
  <% end %>
<% end %>

app/views/shared/_brand.html.erb
<div class="brand">
  <div class="row">
    <div class="span4">
      <h3><%= brand.name %></h3>
      <div>
        <% brand.categories.each do |category| %>
          <span class="badge badge-inverse category-badge pull-right">
            <%= category %>
          </span>
        <% end %>
      </div>
    </div>
    <div class="span8 brand-right">
      <% brand.countries.each do |country| %> 
        <div class='country-label span2'><span class="small">Made in</span><br><%= country %></div>
      <% end %>
      <div class="clearfix"></div>
      <div>
        <blockquote>
          <p class="brand-description"><%= brand.description %></p>
        </blockquote>
      </div>
    </div>
  </div>
  <div class="pull-right">
    <%= link_to 'Full description', "/brands/#{brand.id}" if full_description%> 
    <%= ' | ' if full_description && brand.url.present? %>
    <%= link_to 'Website', brand.url if brand.url.present? %>
  </div>
  <div class="clearfix"></div>
</div>

app/views/shared/_ga.html.erb
<% if Rails.env == 'production' %>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-37825769-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
<% end %>